"""D-010 temporal continuity authority types."""

from umbra_core.temporal.clock import TrustedSample, compute_sample_hash
from umbra_core.temporal.engine import (
    AnchorDelta,
    TemporalAdvancePlan,
    TemporalEngine,
    TemporalEngineError,
    TickTemporalContext,
    build_tick_temporal_context,
)
from umbra_core.temporal.events import (
    ORCHESTRATION_TICK_COMMITTED,
    TEMPORAL_ANCHOR_COMMITTED,
    TEMPORAL_INITIALIZED,
    TemporalAdvanceRecord,
    TemporalContainedEvent,
    TemporalReplayError,
    TemporalTransactionEnvelope,
    advance_record_from_dict,
    advance_record_to_dict,
    apply_advance_plan,
    apply_advance_record,
    build_advance_record,
    build_orchestration_tick_payload,
    build_tick_transaction_envelope,
    envelope_from_dict,
    envelope_to_dict,
    new_transaction_id,
    replay_temporal_state_from_events,
    temporal_state_from_dict,
    temporal_state_to_dict,
)
from umbra_core.temporal.state import (
    AnchorTrustClass,
    TemporalState,
    TimeAnchor,
    WallClockMapping,
    assert_age_never_decreases,
    canonical_serialize,
    compute_definition_hash,
    compute_state_hash,
    sample_temporal_state,
    with_state_hash,
)

__all__ = [
    "AnchorDelta",
    "AnchorTrustClass",
    "ORCHESTRATION_TICK_COMMITTED",
    "TEMPORAL_ANCHOR_COMMITTED",
    "TEMPORAL_INITIALIZED",
    "TemporalAdvancePlan",
    "TemporalAdvanceRecord",
    "TemporalContainedEvent",
    "TemporalEngine",
    "TemporalEngineError",
    "TemporalMigrationContext",
    "TemporalReplayError",
    "TemporalState",
    "TemporalTransactionEnvelope",
    "TickTemporalContext",
    "TimeAnchor",
    "TrustedSample",
    "WallClockMapping",
    "advance_record_from_dict",
    "advance_record_to_dict",
    "apply_advance_plan",
    "apply_advance_record",
    "assert_age_never_decreases",
    "build_advance_record",
    "build_orchestration_tick_payload",
    "build_tick_temporal_context",
    "build_tick_transaction_envelope",
    "canonical_serialize",
    "compute_definition_hash",
    "compute_sample_hash",
    "compute_state_hash",
    "envelope_from_dict",
    "envelope_to_dict",
    "initialize_temporal_epoch",
    "new_transaction_id",
    "replay_temporal_state_from_events",
    "sample_temporal_state",
    "temporal_state_from_dict",
    "temporal_state_to_dict",
    "with_state_hash",
]
