#!/usr/bin/env python3
"""AS-003L static and literal-matrix evidence writer; never imports UMBRA."""
from __future__ import annotations
import hashlib, json, os, subprocess, sys, tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

ROOT=Path(__file__).resolve().parents[1]
EVIDENCE=Path('/srv/ATLAS/100_ACTIVE/Projects/UMBRA-CORE/evidence/live-evidence/umbra-as-003l-regulatory-schedulability-r1')
BASE='5952be53e875351d9aa6016150c0e316d8ba338a'
DRIVES=('energy','fatigue','integrity','stimulation')
CASES=[
 ('C01','both_preserve_all',True,False),('C02','B_loses_energy',True,True),('C03','A_loses_fatigue',True,True),('C04','inverse_energy_fatigue',True,False),('C05','same_deadline_different_service',True,True),('C06','different_deadline_same_service',True,True),('C07','rest_services_fatigue_integrity',True,True),('C08','rest_worsens_stimulation',True,False),('C09','charge_delays_fatigue',True,False),('C10','inspect_consumes_energy',True,False),('C11','delay_destroys_route',True,True),('C12','unknown_completion',False,False),('C13','unknown_route_timing',False,False),('C14','opportunity_absent',False,False),('C15','route_unsupported',False,False),('C16','both_unschedulable',True,False),('C17','strict_continuation_superset',True,True),('C18','crossing_sets',True,False),('C19','candidate_insertion',True,True),('C20','candidate_deletion',True,True),('C21','candidate_permutation',True,True),('C22','identical_candidates',True,False),('C23','coordinate_rescaling',True,True),('C24','label_provenance_equivalence',True,True),('C25','dominance_cycle_probe',True,False),('C26','pending_commitment',True,False),('C27','nonpreemptible_action',True,False),('C28','interruptible_habit',True,False),('C29','comfortable_viable_slack',True,False),('C30','zero_laxity_pre_active',True,True),
]

def now(): return datetime.now(timezone.utc).isoformat()
def shab(b:bytes): return hashlib.sha256(b).hexdigest()
def shaf(p:Path): return shab(p.read_bytes())
def git(*a): return subprocess.check_output(['git',*a],cwd=ROOT,text=True).strip()
def fsyncdir(p:Path):
 fd=os.open(p,os.O_RDONLY|os.O_DIRECTORY)
 try: os.fsync(fd)
 finally: os.close(fd)
def put(name:str,obj:Any):
 EVIDENCE.mkdir(parents=True,exist_ok=True); data=(json.dumps(obj,indent=2,sort_keys=True)+'\n').encode(); fd,tmp=tempfile.mkstemp(prefix='.'+name+'.',dir=EVIDENCE)
 try:
  with os.fdopen(fd,'wb') as f: f.write(data); f.flush(); os.fsync(f.fileno())
  dst=EVIDENCE/name; os.replace(tmp,dst); fsyncdir(EVIDENCE)
  if dst.read_bytes()!=data: raise RuntimeError('readback:'+name)
  return shab(data)
 finally:
  if os.path.exists(tmp): os.unlink(tmp)
def meta(): return {'schema':'AS003L_REGULATORY_SCHEDULABILITY_V1','generated_at':now(),'exact_starting_baseline':BASE,'current_head':git('rev-parse','HEAD'),'production_changes':0,'test_changes':0,'organism_runs':0,'diagnostic_runs':0,'retries':0,'reseeds':0,'analysis_execution':'static source plus literal pure matrices only','pure_proof':{'imports_umbra_core':False,'constructs_runtime':False,'calls_tick_once':False,'executes_embodiment':False,'mutates_persistence':False,'performs_learning':False,'uses_organism_rng':False}}
def src():
 paths=('umbra_core/physiology.py','umbra_core/arbitration.py','umbra_core/runtime.py','umbra_core/embodiment.py','umbra_core/recoverability/view.py','umbra_core/recoverability/contracts.py','umbra_core/self_model/engine.py')
 return {p:shaf(ROOT/p) for p in paths}

def lock():
 ontology={'drive_state':'current physiology from Physiology; not itself an obligation','regulatory_obligation':'conditional record only when supported deadline, corrective capability/opportunity, service demand, effects, and provenance all exist','recovery_capability':'existing CHARGE/REST/INSPECT or route primitive; no candidate creation','environmental_recovery_opportunity':'policy-visible supported observation, never hidden habitat truth','service_demand':'supported worst-case route movement executions plus supported completion lag and terminal action; UNKNOWN if any component lacks HARD_CONTRACT or VERIFIED_OBSERVED_SUPPORT','deadline':'latest supported completion before post-candidate viable-band loss; completion rather than initiation because verified effects occur on completion','laxity':'deadline remaining minus supported service demand; permitted only as SCHEDULABLE / ZERO_OR_NEGATIVE_DEFERABILITY / UNKNOWN, never magnitude ranking','schedulability':'existence of a fixed supported corrective completion before deadline; not a best schedule','hard_safety':'critical-boundary/admissibility remains separate','ordinary_precedence':'only asymmetric feasibility loss, never drive value'}
 rel={'L1':'A precedes B only if A preserves all currently supported individual obligations and B makes at least one unschedulable, with no converse loss','L2':'strict inclusion of fixed finite supported continuation sets only; no count/cardinality/optimization','L3':'A-now vs B-now then one specified recovery only; no open-ended sequence search','prohibited':['EDF/LLF direct selection','minimum laxity','horizon min/max/sum','schedule/future counts','owner priority','weights','utility/reward','planner rollout']}
 cases=[{'id':i,'semantic':s,'supported_facts':support,'unknown_facts':not support,'expected_relation_possible':relation,'authority_layer':'ordinary unless explicitly hard/active boundary'} for i,s,support,relation in CASES]
 d=put('AS003L_REGULATORY_OBLIGATION_ONTOLOGY_LOCK.json',meta()|{'phase':'A_ONTOLOGY_LOCK','ontology':ontology,'relation_families':rel,'source_fingerprints':src(),'lock_rule':'semantic families/cases cannot change after this artifact'})
 put('AS003L_ADVERSARIAL_CASE_LOCK.json',meta()|{'phase':'G_CASE_LOCK','case_count':len(cases),'cases':cases,'lock_dependency_sha256':d,'lock_rule':'no result-specific case alteration permitted'})

def analyze():
 if not (EVIDENCE/'AS003L_ADVERSARIAL_CASE_LOCK.json').exists(): raise RuntimeError('missing adversarial lock')
 parent=Path('/srv/ATLAS/100_ACTIVE/Projects/UMBRA-CORE/evidence/live-evidence/umbra-as-003k-four-drive-regulatory-resolution-r1/AS003K_EVIDENCE_MANIFEST.json')
 put('AS003L_STATE_RECONCILIATION.json',meta()|{'phase':'0_SYNC','head_master_github_at_authority_start':BASE,'governance_start_commit':git('rev-parse','HEAD~1'),'as003k_verdict':'AS003K_ADDITIONAL_CALIBRATION_PRIMITIVE_REQUIRED','as003k_manifest_sha256':shaf(parent),'notion':'AS-003L current authority fetched and refetch-verified','production_test_delta':git('diff','--name-only',BASE+'..HEAD','--','umbra_core','tests').splitlines(),'result':'PASS'})
 put('AS003L_EXECUTION_RESOURCE_MODEL.json',meta()|{'phase':'B_RESOURCE_MODEL','one_final_path':'one selected candidate is committed per arbitration cycle; Governance and Embodiment control execution','smallest_indivisible_unit':'one issued primitive through verified outcome completion','simultaneous_ordinary_actions':False,'pending_execution':'delayed MOVE/APPROACH/RETREAT/ORIENT remains pending in Embodiment; a new ordinary candidate may be chosen but does not complete the pending actuation','preemption':'pending delayed primitive is non-preemptible in current source; higher-level intent is interruptible only before final low-level selection','multi_drive_service':'REST has coupled fatigue/integrity effects; all primitive effects can cross drives','opportunity':'availability and route geometry are policy-visible only when supported; otherwise UNKNOWN','timing':'SelfModel completion intervals exist after verified outcomes; recoverability rejects probabilistic/unknown timing for route claims','resource_model':'conditional single serial execution resource, not an independent-job scheduler','theorem_assumptions':'independent jobs, fixed release/deadline/execution times, and arbitrary preemption are materially false for UMBRA','result':'MAPPING_PARTIALLY_VALID_CONDITIONAL'})
 put('AS003L_EXTERNAL_PRIOR_ART_MATRIX.json',meta()|{'phase':'C_EXTERNAL','sources':[{'source':'https://doi.org/10.1007/978-1-4615-3956-8_3','domain':'deadline scheduling','classification':'REFERENCE','finding':'deadline-minus-service defines laxity but theorem guarantees depend on task assumptions absent in UMBRA; direct EDF/LLF adoption rejected'},{'source':'https://epubs.siam.org/doi/10.1137/0328044','domain':'viability','classification':'REFERENCE','finding':'viability kernels/regulation maps concern constrained feasible evolutions; exact construction is a control/selection problem, not automatically a non-planning local relation'},{'source':'https://www.sciencedirect.com/science/article/abs/pii/S0303264726002121','domain':'controllable futures','classification':'REJECT','finding':'explicitly compares policy-selection models and joint scores; prohibited optimization architecture'},{'source':'https://www.sciencedirect.com/science/article/abs/pii/S0149763421000750','domain':'motivational competition','classification':'REFERENCE','finding':'temporal/interruptible motivational competition is biologically plausible but does not provide UMBRA scheduling semantics'}],'result':'REFERENCE_ONLY_NO_ALGORITHM_IMPORT'})
 l1=[]
 for i,s,supported,possible in CASES:
  relation=bool(supported and possible and i in {'C02','C03','C05','C06','C07','C11','C17','C30'})
  l1.append({'id':i,'semantic':s,'supported':supported,'l1_precedence':relation,'close02z_residual_expected':not relation,'reason':'individual feasibility loss' if relation else ('UNKNOWN blocks relation' if not supported else 'both feasible, both fail, cross-loss, or relation silent')})
 applicable=[x for x in l1 if x['supported']]; eliminations=[x for x in l1 if x['l1_precedence']]
 put('AS003L_FEASIBILITY_NOT_UTILITY_PROOF.json',meta()|{'phase':'D_FEASIBILITY_BOUNDARY','permitted_output':'only directional feasibility loss; laxity is reduced to SCHEDULABLE/ZERO_OR_NEGATIVE_DEFERABILITY/UNKNOWN','explicitly_absent':['minimum-laxity selection','deadline ranking','sum/average/min/max','schedule count','feasible-future count','missed-obligation value'],'result':'L1_IS_FEASIBILITY_NOT_UTILITY'})
 put('AS003L_BOUNDEDNESS_AND_PLANNING_BOUNDARY.json',meta()|{'phase':'F_BOUNDARY','drive_ceiling':4,'L1':'one immediate candidate plus independently supported one-obligation recovery check; bounded and read-only but insufficient for joint obligations','L2_upper_bound_if_idealized':'4! = 24 orderings for four single-service obligations before route alternatives, delayed commitments, effect branches, releases, and opportunity changes','L2_actual_requirement':'to establish Feasible(B) subset Feasible(A), source must choose/project multiple future corrective actions and their order under coupled effects and changing opportunity/timing support','classification':'PLANNING_BOUNDARY','reason':'the useful joint relation is an explicit bounded future-action sequence search. Finite cardinality does not erase its planning character.','result':'L2_NOT_ADOPTABLE'})
 put('AS003L_RELATION_INTEGRITY_PROOF.json',meta()|{'phase':'H_INTEGRITY','L1_properties':{'irreflexive':'PASS','asymmetric':'PASS by one-way feasibility loss condition','candidate_order':'PASS','proposal_source_and_provenance':'PASS semantic facts only','unknown':'PASS blocks','scalar_total_owner_priority':'PASS absent','multi_drive_service':'represented as one coupled service effect, not double counted','hard_safety':'PASS separate'},'L2_properties':{'strict_set_inclusion':'mathematically acyclic if exact','implementation_status':'NOT_ADOPTABLE because obtaining sets requires prohibited multi-step future service-order projection'},'cycle_probe':'No L1 cycle; crossing obligations are mutually non-dominating. No tie-break was added.','result':'L1_INTEGRITY_PASS_L2_BOUNDARY_STOP'})
 put('AS003L_SELECTION_PRESSURE_AUDIT.json',meta()|{'phase':'I_PRESSURE','locked_case_count':30,'supported_cases':len(applicable),'l1_precedence_cases':len(eliminations),'l1_supported_case_fraction':round(len(eliminations)/len(applicable),6),'unknown_blocked_cases':len([x for x in l1 if not x['supported']]),'close02z_residual_cases':len([x for x in l1 if x['close02z_residual_expected']]),'structural_result':'L1 expresses the tight feasibility-loss distinction absent in AS-003K, but leaves inverse/coupled obligations silent. Joint feasible-continuation set inclusion would add pressure only by performing prohibited future-service sequencing.','result':'L1_USEFUL_BUT_NOT_SUFFICIENT'})
 put('AS003L_AS002_COMPATIBILITY_AUDIT.json',meta()|{'phase':'J_AS002','L1':'could be emitted as a separate UNKNOWN-aware feasibility proposition without total/weight/source priority and with simultaneous order-independent comparison','L2':'would require future action-order construction; not adopted','protected_authority':{'candidate_generation':'unchanged','hard_safety':'unchanged','critical_active_recovery':'unchanged','Governance':'unchanged','Embodiment':'unchanged','VerifiedOutcome_learning':'unchanged','CLOSE02Z':'residual unchanged'},'result':'L1_COMPATIBLE_BUT_INSUFFICIENT; L2_PLANNING_BOUNDARY'})
 put('AS003L_HYPOTHESIS_CHALLENGE.json',meta()|{'phase':'K_CHALLENGE','answers':{'obligations':'conditionally analogous only when deadline, opportunity, capability and duration are supported','serial_resource':'one final primitive path exists, but delayed/nonpreemptible commitment weakens textbook analogy','viable_loss_deadline':'valid conditional completion deadline, not direct drive value','service_demand':'valid only as supported opportunity-specific route plus completion evidence','coupling':'invalidates independent-job assumptions and makes joint feasibility order-sensitive','opportunity_uncertainty':'UNKNOWN must block relation; present source lacks universal timing support','bounded_feasibility':'enumerating future corrective order is planning despite four-drive bound','organism_competition':'L1 captures real deferment danger; L2 becomes a plan constructor','hidden_priority':'avoided in L1; reappears if orders are selected/optimized','within_viable_conflict':'partially resolved only where one immediate action destroys supported feasibility','residual_conflicts':'legitimate if both continuations remain feasible','resource_use':'does not justify implementation because full useful relation crosses planning boundary'},'result':'PLANNING_BOUNDARY_REQUIRED'})
 put('AS003L_VERDICT.json',meta()|{'terminal_verdict':'AS003L_PLANNING_BOUNDARY_REQUIRED','ontology':'conditional obligation/deadline/service concepts are lawful only with existing support; missing evidence remains UNKNOWN','L1':'lawful non-utility local feasibility precedence, integrity-pass, but insufficient as full four-drive resolver','L2':'the needed joint continuation-set relation requires future corrective service-order projection and is planning even with theoretical 4! obligation permutations','L3':'NOT_REQUIRED after planning-boundary finding','exact_blocked_assumption':'that joint regulatory schedulability can be determined without constructing a multi-step future action/service order under coupled effects, pending commitments, and opportunity-dependent routes','recommendation':'NONE; return to Architect. Do not start AS-003M or any successor.','close02z':'residual only; must not become a scheduling score.'})
def manifest():
 files=sorted(p for p in EVIDENCE.glob('AS003L_*') if p.name!='AS003L_EVIDENCE_MANIFEST.json')
 put('AS003L_EVIDENCE_MANIFEST.json',meta()|{'artifact_count':len(files),'artifacts':[{'name':p.name,'sha256':shaf(p),'bytes':p.stat().st_size} for p in files],'readback':'PASS','result':'PASS'})
if __name__=='__main__':
 if len(sys.argv)!=2 or sys.argv[1] not in {'lock','analyze','manifest'}: raise SystemExit('usage: as003l_research.py {lock|analyze|manifest}')
 {'lock':lock,'analyze':analyze,'manifest':manifest}[sys.argv[1]]()
